### PR TITLE
Add a link to Philosophy from Committers credo

### PR DESCRIPTION
**Pull request by danielbachhuber**
See #30

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@gitlost FYI - you can merge too, if you approve of the changes.

**Comment by gitlost** [comment]
Ok, ta, not very sure of the protocol.

**Comment by danielbachhuber** [comment]
> Ok, ta, not very sure of the protocol.

How could we better document this?

**Comment by gitlost** [comment]
Well perhaps I should initiate some draft document on it, perhaps, and also docs on setting up a local test environment and debugging behat etc. for contributors. I hope to do this over the weekend.

**Comment by danielbachhuber** [comment]
> Well perhaps I should initiate some draft document on it, perhaps, and also docs on setting up a local test environment and debugging behat etc. for contributors.

That'd be great! We also have https://github.com/wp-cli/handbook/issues/17, which I've been meaning to get to.

> I hope to do this over the weekend.

No rush — whenever convenient for you.

**Pull request merged**
