### PR TITLE
Add to hosting-companies.md

### PR DESCRIPTION
**Pull request by at-benni**
Added two hosting companies with wp-cli and one click wordpress installation methods

### CODE REVIEW

**Comment by ernilambar** [comment]
@at-benni Can you please clarify whether these hosts provide WPCLI by default for WordPress? I could not find anything mentioned in their website regarding this?

**Comment by at-benni** [comment]
Hey, at domaintechnik one this page: https://www.domaintechnik.at/remote-access.html
There is "Vorinstallierte Software und wichtige Dateipfade"  which means "Pre-installed software and important file paths".
There you can find wp-cli.

alldomains.hosting is the same company acting in a different country (austria = domaitnechnik, alldomainsohsting = germany) and wp-cli is also available, I can't find it one the website

**Comment by ernilambar** [comment]
@at-benni  Ok. Another PR has been just merged in the same file. Can you please fix the merge conflict? Then it would be good to go.

**Comment by at-benni** [comment]
thanks @ernilambar I have resolved the conflict

**Review by ernilambar — APPROVED** [review]

**Pull request merged**
