### PR TITLE
Beginners documentation > added 

### PR DESCRIPTION
**Pull request by BenjaminZekavica**
Hallo I added the beginners docs. releated to the issue: #297

### CODE REVIEW

**Comment by BenjaminZekavica** [comment]
@schlessera Please, do you can check this PR? :)

**Review by danielbachhuber — COMMENTED** [review]
Thanks for the PR, @BenjaminZekavica !

I'm not sure this documentation makes sense in our handbook. We'll need to discuss first, and get back on it.

If we do accept it, it will need some editing.

**Comment by BenjaminZekavica** [comment]
@danielbachhuber I added it because in the Issue was an Idea to add some beginner sections.

**Comment by BenjaminZekavica** [comment]
@danielbachhuber I compress it to the quick start handbook (See PR):
#515

**Pull request closed without merging**
