### PR TITLE
Added "Sort plugins or themes by certain column(s)" to "Snippets"

### PR DESCRIPTION
**Pull request by porg**
- In the H2 section "Snippets" I transformed all sub-sections into proper H3s, to get proper permanent anchor-links for easy linking and a TOC (as it grows over time!)
- Then I added my particular H3: Sort plugins or themes by certain column(s)

### CODE REVIEW

**Comment by porg** [comment]
One more question: Which manpages/sections link to `shell-friends.md` ?

- When I search for [shell-friends.md in the repo](https://github.com/search?q=repo%3Awp-cli%2Fhandbook%20%20shell-friends.md&type=code) I currently only find the file itself, and an entry in the manifest. But no incoming links.

- If it has no incoming links from a main help document, no-one will ever discover the content.

- Glad for any info on that.

**Comment by danielbachhuber** [comment]
Looks great, thanks!

> One more question: Which manpages/sections link to `shell-friends.md` ?

It's linked to from these pages:
* https://make.wordpress.org/cli/handbook/
* https://make.wordpress.org/cli/handbook/guides/quick-start/
* https://make.wordpress.org/cli/handbook/contributions/philosophy/

**Review by danielbachhuber — APPROVED** [review]

**Comment by danielbachhuber** [comment]
> Is it also mentioned from somewhere within the command line help itself?

It's not, no. It might make sense to link to the handbook from `wp help`, but probably not an individual document.

**Comment by porg** [comment]
Maybe at the very bottom of `wp help` insert

SEE ALSO:

> `wp help shell-friends`    —  Get some tips & tricks how you can make the most of wp-cli in combination with other CLI apps. Composability is a [key philosophy](https://make.wordpress.org/cli/handbook/philosophy/) of WP-CLI!

Or if not made available as a help page of the app, then:

> SEE ALSO:
> 
> https://make.wordpress.org/cli/handbook/references/shell-friends/
> 
> Get some tips & tricks how you can make the most of wp-cli in combination with other CLI apps. Composability is a [key philosophy](https://make.wordpress.org/cli/handbook/philosophy/) of WP-CLI!

- Many Terminal apps allow clicking hyperlinks (with right-click or click + modifier key).
- Or copy and pasting into a web browser will also do.
- Certainly this measure would help discoverability a bit.

**Comment by porg** [comment]
- Submitted: https://github.com/wp-cli/wp-cli/issues/5794

**Pull request merged**
