### PR TITLE
Updating profile.md with more hooks showing for the profile stage command

### PR DESCRIPTION
**Pull request by josevarghese**
Added with more hooks showing for the `wp profile stage bootstrap --fields=hook,time,cache_ratio --spotlight` like `setup_theme   `and `after_setup_theme`.

### CODE REVIEW

**Review by wojtekn — APPROVED** [review]

**Comment by wojtekn** [comment]
Actually, isn't this one auto-generated, too?

**Comment by ernilambar** [comment]
Yes. It should be updated here - https://github.com/wp-cli/profile-command/blob/main/src/Command.php

**Comment by josevarghese** [comment]
Done. Created a PR with the help of @wojtekn over here: https://github.com/wp-cli/profile-command/pull/191

**Comment by ernilambar** [comment]
Closing in favor of https://github.com/wp-cli/profile-command/pull/191

**Pull request closed without merging**
