### PR TITLE
Improve examples for is-installed usage

### PR DESCRIPTION
**Pull request by petertwise**

### CODE REVIEW

**Review by swissspidy — APPROVED** [review]
Looks reasonable, thanks for your contribution!

**Comment by petertwise** [comment]
Thanks for including. 

FYI, the message "Error: This does not seem to be a WordPress installation." is not suppressed by the --quiet flag. 
Seems like that's the best/reasonable behavior for 99% of other WP CLI commands, so I figured best to solve by documenting for others how to use `2>dev/null` in this case were you might actually mean to run the command outside of WP sometimes instead of trying to ask to have some crazy workaround/exception for the --quiet flag.

**Comment by danielbachhuber** [comment]
@petertwise This documentation is actually generated from the codebase on every release.

Can you submit your changes against wp-cli/core-command?

https://github.com/wp-cli/core-command/blob/164455896f45861c8d1bcc3f9b4de4deceef8cf4/src/Core_Command.php#L351-L359

Otherwise, they'll be blown away when the documentation is regenerated.

**Comment by petertwise** [comment]
Good call - thanks for catching that.

https://github.com/wp-cli/core-command/pull/237

**Comment by swissspidy** [comment]
Whoops my bad for not realizing this is the handbook repo!

**Pull request closed without merging**
