### PR TITLE
Added AnsiPress

### PR DESCRIPTION
**Pull request by MiteshShah**
https://github.com/AnsiPress/AnsiPress/blob/develop/roles/website/tasks/wp.yml#L6L32

### CODE REVIEW

**Comment by MiteshShah** [comment]
@danielbachhuber Not sure what's breaks but its does not looks good on website 
https://make.wordpress.org/cli/handbook/tools/#misc

I guess extra space cause this issue :(

**Comment by danielbachhuber** [comment]
> I guess extra space cause this issue :(

Fixed e9beccdc5ce77961ba482b2101a142addf85590e

**Comment by MiteshShah** [comment]
@danielbachhuber  Still same :(
I'd tested on Githubmark Down and syntax looks good to me 
Any idea what cause this silly issue ?

screen shot 2017-03-01 at 8 24 26 pm

**Comment by danielbachhuber** [comment]
> Still same :(

The content is synced on a 15 minute cron, so you'll need to wait a few more minutes.

**Comment by MiteshShah** [comment]
Thanks for your help :)

**Pull request merged**
